server:
  port: 8083

spring:
  application:
    name: signaling-service
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]
      - optional:file:../../.env[.properties]
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

kurento:
  ws:
    url: ${KURENTO_WS_URL:ws://localhost:8888/kurento}
